spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/admindb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
  devtools:
    restart:
      enabled: true
      exclude: static/**, public/**
service:
  famme:
    url: https://famme.no

scheduler:
  cronExpression: 0 */1 * * * *

server:
  port: 8081